language: node_js

node_js:
    - "node"
    - "7"
    - "6.10"
    - "6"

install:
    - npm install

before_script:
    - npm install html-loader ngtemplate-loader

script:
    - npm test
    - npm run linter
    - npm run one-directive
    - npm run many-directives
    - npm run multiple-directives

cache:
    directories:
        - "node_modules"
