language: node_js

os:
  - linux
  - osx
  - windows

node_js:
  - "node"
  - "14"
  - "12"
  - "10"

install:
  - npm ci

jobs:
  include:
    - env:
      - WEBPACK_VERSION=4
      - WEBPACK_CLI_VERSION=3
    - env:
      - WEBPACK_VERSION=5
      - WEBPACK_CLI_VERSION=4

script:
  - npm install webpack@$WEBPACK_VERSION webpack-cli@WEBPACK_CLI_VERSION
  - npm test
  - npm run linter
  - npm run one-directive
  - npm run many-directives
  - npm run multiple-directives
  - npm run absolute-paths
  - npm run separated-templates

cache:
  directories:
    - "node_modules"
