language: node_js

node_js:
  - 'node'
  - '12'
  - '10'
  - '8'

install:
  - npm install

script:
  - npm test
  - npm run linter
  - npm run one-directive
  - npm run many-directives
  - npm run multiple-directives
  - npm run absolute-paths

cache:
  directories:
    - 'node_modules'
