language: node_js

os:
  - linux
  - osx
  - windows

node_js:
  - "node"
  - "14"
  - "12"
  - "10"

install:
  - npm ci

script:
  - npm test
  - npm run linter
  - npm run one-directive
  - npm run many-directives
  - npm run multiple-directives
  - npm run absolute-paths
  - npm run separated-templates

cache:
  directories:
    - "node_modules"
